### ISSUE TITLE
DX issue, graphics.cpp after try to start capture.

### ISSUE THREAD

**Issue by kmshort** [kebby/Capturinha#1]
Hey,
I've already posted this on Pouet, but I'll put it here again as it's more appropriate.
When I try to start a capture, it fails, with error message

```
C:\code\ScreenCap\graphics.ccp(855): 
D3D call failed (887a002d).
```

Not sure what's up here. Dxdiag (v 10.00.19041.0928 64-bit Unicode) tells me I'm running DirectX 12.

FWIW, there is no C:\code\ScreenCap\graphics.ccp file, nor directory; but graphics.cpp line 855 is:

```
DXERR(D3D11CreateDevice(Output.Adapter, Output.Adapter.IsValid() ? D3D_DRIVER_TYPE_UNKNOWN : D3D_DRIVER_TYPE_HARDWARE, NULL, flags, levels, _countof(levels), D3D11_SDK_VERSION, dev0, &FeatureLevel, ctx0));
```

cheers
K

**Comment by kebby** [comment]
Fixed here; https://github.com/kebby/Capturinha/commit/4e675d634a05a78e4c0680a14e95f9b27af32bc8 - that was an embarrassing one.
